spring.application.name=demo
management.endpoints.web.exposure.include=health,info,mappings
#management.endpoints.web.exposure.exclude=health,info,mappings
management.info.env.enabled=true

info.app.name=java starter
info.app.description=A simple Java starter project to practice core concepts
info.app.version=1.0.0

coach.name=John
team.name=Doe

server.port=8080
server.servlet.context-path=/